### ISSUE TITLE
Incorrect classification when PVS >1

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/variant_classification_DB#40]
Calculates 'VUS - criteria not met' instead of 'Pathogenic' when number of PVS codes is more than 1

https://github.com/AWGL/variant_classification_DB/blob/9a4e599dd2924057a0e38386a0650df59cbadeee/acmg_db/utils/acmg_classifier.py#L133

**Comment by josephhalstead** [comment]
closed in pull request #41
