### ISSUE TITLE
PVS1

### ISSUE THREAD

**Issue by LauraMcCluskey7** [AWGL/variant_classification_DB#5]
If a criteria is adjusted to "PV" and "PVS1" is already present, "VUS" is outputted.

**Comment by josephhalstead** [comment]
Possible change line 341 of models.py - def strength_options() - don't allow user to change strength to either PV or BA for ACMG codes which are not already this category.

Additionally add extra checks to make sure multiple PV or BA input is caught

**Comment by josephhalstead** [comment]
Fixed in commit c52c30d66
